ARG ELASTIC_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/logstash/logstash:${ELASTIC_VERSION}
#RUN logstash-plugin install logstash-input-http
#RUN logstash-plugin install logstash-filter-json
#RUN logstash-plugin install logstash-output-elasticsearch